# Python Basics


In [10]:
# Printing in Python
print("Hello, Hi Welcome to Python for AI" )
print(" Kamil !!! ")

Hello, Hi Welcome to Python for AI
 Kamil !!! 


### Variables

In [11]:
# defining the variables in python: 
var1 = 10
var2 = 3.369
var3 = "Hello"

print(var1, var2, var3)
print(type(var1), type(var2), type(var3))

# In python we dont need to mention the datatype unlike java and other languages

10 3.369 Hello
<class 'int'> <class 'float'> <class 'str'>


In [12]:
print(type(var1))
print(type(var2))
print(type(var3))

var1="hello"
print(type(var1))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'str'>


In [13]:
pi = 3.14
print("Value of pi is ", pi)

Value of pi is  3.14


### Assignment

In [15]:
# Assigning same values to the multiple variables
var1 = var2 = var3 = 1
print(var1,' ', var2,' ', var3)

# Assigning Different values to variables in a single expression
var1, var2, var3 = 3, 6, "nine"
print(var1,' ', var2,' ', var3)

1   1   1
3   6   nine


### Slicing

In [32]:
# String operations

str = "Hello AI World" 
length = len(str)
print(str[length-2:])
print(str)
print(str[0])
print(str[6:9])
print(str[3:])
print(str[:6])
print(str * 3) 
str1 = str * 10
print(str1)
print(str + " Order")


ld
Hello AI World
H
AI 
lo AI World
Hello 
Hello AI WorldHello AI WorldHello AI World
Hello AI WorldHello AI WorldHello AI WorldHello AI WorldHello AI WorldHello AI WorldHello AI WorldHello AI WorldHello AI WorldHello AI World
Hello AI World Order


### Data types

In [43]:
# Python Lists
list = ['abcd', 369, 786, 'Solomon', 'David', 3.14]

# A tuple. Tuples are immutable, i.e. cannot be edit later
tuple = ('abcd', 369, 786, 'Solomon', 'David', 3.14)

print(list[:3])
print(list[3][0])
print(list[3][3])
print(list[3][6])
print(tuple[1:3])

['abcd', 369, 786]
S
o
n
(369, 786)


In [55]:
# Lists are ordered sets of objects, whereas dictionaries are unordered sets.
# But the main difference is that items in dictionaries are accessed 
# via keys and not via their position.

tel = {'David': 786, 'Solomon': 369}
tel['David'] = 1786
print(tel)
del tel['David']
print(tel)
tel['Abraham'] = 3323
print(tel.keys())
print(sorted(tel.keys()))
print(sorted(tel.values()))
print('Rava' in tel)
print('Solomon' in tel)
print('Yusuf' not in tel)




{'David': 1786, 'Solomon': 369}
{'Solomon': 369}
dict_keys(['Solomon', 'Abraham'])
['Abraham', 'Solomon']
[369, 3323]
False
True
True


###  Conditioning and looping

In [56]:
# Square of Even numbers

for i in range(10):
    if i % 2 == 0:
        print("Square of ",i,"is :", i * i)
    
    else:
        print(i, "is odd number")
print("End Loop")
         

Square of  0 is : 0
1 is odd number
Square of  2 is : 4
3 is odd number
Square of  4 is : 16
5 is odd number
Square of  6 is : 36
7 is odd number
Square of  8 is : 64
9 is odd number
End Loop


### Built-in Functions

In [ ]:
print("sum of the array:", sum([3,6,9]))
print("Length of array:", len([1,2,3,4,5,6,7,8,9,10]))
print("Absolute value: ", abs(-369))
print("Round Value: ", round(3.1444444444))
value = 12.2456
formatted_float = "{:.2f}".format(value)
print("Float", formatted_float)
print(f"Float, {value:.2f}")

sum of the array: 18
Length of array: 10
Absolute value:  369
Round Value:  3
Float 12.25
Float, 12.25


### Functions

In [76]:
# Area of Rectangle
def area(len, wid):
    return len*wid, 2*(len + wid)

ap = area(10, 20)
print("Area of rectangle:", ap[0])  # Area
print("Perimeter of rectangle:", ap[1])  # Perimeter

Area of rectangle: 200
Perimeter of rectangle: 60


### NumPy 
* Numpy is the fundamental package for numerical computing with Python.
* a powerful N-dimensional array object
* useful linear algebra, Fourier transform, and random number capabilities

In [81]:
import numpy as np

a = np.array([7,8,6])
b = np.array([3,6,9])

print("Matrix A\n", a)
print("\nMatrix B\n", b)

print("\nMatrix Addition A + B \n", a + b)
print("\nAddition using Broadcasting A + 3\n", a + 3)

Matrix A
 [7 8 6]

Matrix B
 [3 6 9]

Matrix Addition A + B 
 [10 14 15]

Addition using Broadcasting A + 3
 [10 11  9]


In [82]:
# Lets go for a 2D matrix
c = np.array([[0, 1, 2],[3, 4, 5],[6, 7, 8]])
d = np.array([[1, 2, 3],[1, 2, 3],[1, 2, 3]])

e = np.array([1, 2, 3])

print("Matrix C\n", c)
print("Matrix D\n", d)
print("Matrix E\n", e)

print("Regular matrix addition C+D\n", c + d)

print("Addition using Broadcasting C+E\n", c + e)

Matrix C
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Matrix D
 [[1 2 3]
 [1 2 3]
 [1 2 3]]
Matrix E
 [1 2 3]
Regular matrix addition C+D
 [[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]
Addition using Broadcasting C+E
 [[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]


In [85]:
test_ones = np.ones((3,3))
print("Matrix Ones M: \n", test_ones)

Matrix Ones M: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [86]:
print("Dimension of test_ones:", test_ones.shape)
print("Dimension of a: ",a.shape)
print(test_ones + a)

Dimension of test_ones: (3, 3)
Dimension of a:  (3,)
[[8. 9. 7.]
 [8. 9. 7.]
 [8. 9. 7.]]
